package com.soaint.entities;
// Generated 23-abr-2021 14:51:11 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TarTarea generated by hbm2java
 */
@Entity
@Table(name = "tar_tarea", catalog = "prueba")
public class TarTarea implements java.io.Serializable {

	private Integer tarId;
	private String tarDescripcion;
	private Date tarFechaCreacion;
	private Boolean vigente;

	public TarTarea() {
	}

	public TarTarea(String tarDescripcion, Date tarFechaCreacion, Boolean vigente) {
		this.tarDescripcion = tarDescripcion;
		this.tarFechaCreacion = tarFechaCreacion;
		this.vigente = vigente;
	}

	@Id
	@Column(name = "tar_id", unique = true, nullable = false)
	public Integer getTarId() {
		return this.tarId;
	}

	public void setTarId(Integer tarId) {
		this.tarId = tarId;
	}

	@Column(name = "tar_descripcion", length = 100)
	public String getTarDescripcion() {
		return this.tarDescripcion;
	}

	public void setTarDescripcion(String tarDescripcion) {
		this.tarDescripcion = tarDescripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tar_fecha_creacion", length = 10)
	public Date getTarFechaCreacion() {
		return this.tarFechaCreacion;
	}

	public void setTarFechaCreacion(Date tarFechaCreacion) {
		this.tarFechaCreacion = tarFechaCreacion;
	}

	@Column(name = "vigente")
	public Boolean getVigente() {
		return this.vigente;
	}

	public void setVigente(Boolean vigente) {
		this.vigente = vigente;
	}

}
